Repository today-they-learned/peacepiece_api, pull requests merged in 2022-08, with the labels that each got.

#38 refactor: settings 를 환경별로 분리하여 자연스럽게 사용할 수 있도록 함.
  .pre-commit-config.yaml
  config/asgi.py
  config/settings/__init__.py
  config/settings/base.py
  config/settings/development.py
  config/settings/production.py
  config/settings/test.py
  config/wsgi.py
  manage.py
Labels: 리팩토링

#39 refactor: CORS 설정 추가
  config/settings/base.py
Labels: 환경설정

#41 어드민과 모델을 이후에 더 쉽게 확인하고 사용할 수 있게 수정
  article/admin/article.py
  article/migrations/0002_article_created_at_article_updated_at.py
  article/models/article.py
  challenge/admin/category.py
  challenge/admin/challenge.py
  challenge/admin/challenge_category.py
  challenge/admin/challenge_reminder.py
  challenge/admin/challenge_suggestion.py
  challenge/migrations/0005_category_created_at_category_updated_at_and_more.py
  challenge/models/category.py
  challenge/models/challenge.py
  challenge/models/challenge_category.py
  challenge/models/challenge_reminder.py
  challenge/models/challenge_suggestion.py
  config/admin.py
  config/models.py
  point/migrations/0003_point_created_at_point_updated_at.py
  point/models/point.py
  user/migrations/0002_user_created_at_user_updated_at.py
  user/models/user.py
Labels: 모델, 어드민

#42 restframework 관련 설정 추가 및 기존에 lint 적용안되어있던 부분들 적용
  .pre-commit-config.yaml
  article/migrations/0001_initial.py
  article/migrations/0002_article_created_at_article_updated_at.py
  challenge/admin/__init__.py
  challenge/admin/challenge_category.py
  challenge/admin/challenge_reminder.py
  challenge/admin/challenge_suggestion.py
  challenge/apps.py
  challenge/migrations/0001_initial.py
  challenge/migrations/0002_category_challengecategory_challenge_categories.py
  challenge/migrations/0002_challengesuggestion.py
  challenge/migrations/0003_challengereminder.py
  challenge/migrations/0005_category_created_at_category_updated_at_and_more.py
  challenge/models/__init__.py
  challenge/models/category.py
  challenge/models/challenge.py
  challenge/models/challenge_category.py
  challenge/models/challenge_reminder.py
  challenge/models/challenge_suggestion.py
  config/admin.py
  config/authentications.py
  config/exceptions/__init__.py
  config/exceptions/exception_handler.py
  config/paginations.py
  config/settings/base.py
  config/settings/production.py
  config/urls.py
  notification/admin/notification.py
  notification/migrations/0001_initial.py
  notification/migrations/0002_initial.py
  notification/models/notification.py
  point/admin/point.py
  point/migrations/0001_initial.py
  point/migrations/0002_initial.py
  point/migrations/0003_point_created_at_point_updated_at.py
  point/models/point.py
  pyproject.toml
  user/admin/user.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/0002_user_created_at_user_updated_at.py
  user/models/user.py
  user/urls.py
Labels: 리팩토링

#40 Challenge suggestion feedback model
  challenge/admin/__init__.py
  challenge/admin/challenge_suggestion_feedback.py
  challenge/migrations/0003_challengesuggestionfeedback.py
  challenge/models/__init__.py
  challenge/models/challenge_suggestion_feedback.py
Labels: 모델

#47 user | avatar 추가 및 serializer 설정 추가
  .gitignore
  config/settings/base.py
  config/settings/production.py
  config/urls.py
  requirements.txt
  user/migrations/0003_user_avatar.py
  user/models/user.py
  user/serializers/__init__.py
  user/serializers/user_abstract_serializer.py
  user/serializers/user_jwt_serializer.py
Labels: 환경설정, 모델

#58 ChallengeSuggestionFeedback API 개선
  challenge/serializers/challenge_suggestion_feedback_serializer.py
  challenge/urls.py
  challenge/views/__init__.py
  challenge/views/challenge_suggestion_feedback_api_view.py
  challenge/views/challenge_suggestion_feedback_view_set.py
Labels: refactor

#60 pipenv settings
  Pipfile
  Pipfile.lock
  requirements.txt
  runtime.txt
Labels: enhancement, refactor

#59 article-images 연결관계 추가 및 관련 API 설정
  article/migrations/0005_article_images.py
  article/models/article.py
  article/serializers/__init__.py
  article/serializers/article_list_serializer.py
  article/serializers/article_serializer.py
  article/serializers/article_update_serializer.py
  article/views/article_view_set.py
  file_manager/migrations/0003_articleimage.py
  file_manager/models/__init__.py
  file_manager/models/article_image.py
Labels: enhancement

#67 Article API에 Challenge 연결
  article/admin/__init__.py
  article/admin/article.py
  article/admin/challenge_article.py
  article/migrations/0007_delete_challengearticle.py
  article/migrations/0008_article_challenge.py
  article/migrations/0009_article_unique_challenge_article_by_user.py
  article/migrations/0010_alter_article_images.py
  article/models/__init__.py
  article/models/article.py
  article/models/challenge_article.py
  article/serializers/article_list_serializer.py
  article/serializers/article_serializer.py
  article/serializers/article_update_serializer.py
  article/views/article_view_set.py
  config/exceptions/exception_handler.py
  config/settings/base.py
  config/utils.py
Labels: 리팩토링, 환경설정, 모델, API 개발

#69 categories 목록 조회 API 추가
  challenge/models/category.py
  challenge/serializers/__init__.py
  challenge/urls.py
  challenge/views/__init__.py
  challenge/views/category_list_api_view.py
Labels: 모델, API 개발

#70 challenge_reminder API 추가
  challenge/migrations/0012_challengereminder_unique_category_by_user.py
  challenge/models/challenge_reminder.py
  challenge/serializers/__init__.py
  challenge/serializers/challenge_reminder_serializer.py
  challenge/urls.py
  challenge/views/__init__.py
  challenge/views/challenge_reminder_api_view.py
  config/exceptions/exception_handler.py
Labels: 모델, API 개발

#71 JWT 만료 기간을 임시로 늘림
  config/settings/base.py
Labels: 환경설정
